# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: format
        name: format code
        entry: make fmt
        types: [go]
        language: golang
        pass_filenames: false
